### ISSUE TITLE
Implement servo.c for science nucleo

### ISSUE THREAD

**Issue by tabiosg** [umrover/embedded-testbench#166]
Use this as a reference
https://github.com/umrover/embedded-testbench/blob/guts/science-dev/science-dev/Core/Inc/servo.h

**Comment by tabiosg** [comment]
https://github.com/umrover/embedded-testbench/blob/rover-22/science/science_nucleo_g0/Core/Src/servo.c

**Comment by tabiosg** [comment]
Check out of guts/science-dev and make a new branch called something like eric/servo or wis/servo. Create the servo.c file in Core/Src folder. Use [this ](https://github.com/umrover/embedded-testbench/blob/rover-22/science/science_nucleo_g0/Core/Src/servo.c) code as reference for working code. Feel free to change up the header file if needed

**Comment by sashreek1** [comment]
Here's the old science servo code:
https://github.com/umrover/embedded-testbench/blob/rover-22/science/science_nucleo_g0/Core/Src/servo.c

**Comment by sashreek1** [comment]
PWM signal resources :
https://deepbluembedded.com/stm32-pwm-example-timer-pwm-mode-tutorial/

**Comment by tabiosg** [comment]
Closed by #175
